fix: use identifier name for positional args (#10435)
fixes a corner case where a model has properties that collide with
identifier names:


``/mnt/vss/_work/1/s/sdk/voicelive/Azure.AI.VoiceLive/src/Generated/VoiceLiveModelFactory.cs(2135,44):
error CS1525: Invalid expression term 'object'
[/mnt/vss/_work/1/s/sdk/voicelive/Azure.AI.VoiceLive/src/Azure.AI.VoiceLive.csproj::TargetFramework=net10.0]``